### ISSUE TITLE
S7 官网页面更新

### ISSUE THREAD

**Issue by 121812** [SeeDAO-OpenSource/seedao.xyz#1]
## 悬赏介绍
> 在该issue下填写认领即可申领，对接人将按时间顺序对申领人回复认领成功，认领成功后三天内需提交该需求PR，成功合并后即可按SeeDAO规则认领赏金。

- 悬赏名称：S7 官网页面更新

- 需求描述：
  - 展示栏增加SNS成员数据
  - 城邦之旅 - onboarding 改为 社区Wiki
  - 城邦之旅 - 三层提案 移除
  - 城邦之旅 - 身份体系 移除
  - 增加开源地址
  - 生态伙伴更新
  - 官网数据更新 

**部分更新内容与源代码需联系对接人获取**

- 悬赏金额：75 USDC

- 对接人：Forever121 
- Discord联系方式：forever_121

**Comment by rectinajh** [comment]
认领

**Comment by 121812** [comment]
> 认领

认领成功，请在三天内提交该需求PR

**Comment by 121812** [comment]
@rectinajh PR在昨日提交，已通过，悬赏结束。
